sudo: false
language: ruby
services:
  - docker
before_install:
  - git clone --depth 1 https://github.com/seiferma/Docker_BuildUtils.git /tmp/BuildUtils
  - . /tmp/BuildUtils/travisSetup.sh
script:
  - travisBuildDockerhub.sh
deploy:
  provider: script
  script: travisDeployDockerhub.sh
  on:
    branch: master
env:
  global: 
    - IMAGE_NAME=seiferma/elasticsearch-ingestattachment
    - secure: "dLv++7aD0o01h73qPcX9CDR1S8BFOQb5Lwj3czTHnltrpJ5QINLqtam560z26CVmVGvL9+Bfz6HSzA39tvbdkLj2OrIT2F8Pq6eRI/Ckly0UkCRbbECJw5IKrdw8YVxUd0LjDKllH5hjf1rECSoaZi8kzFaP6vs6F9QPMdS5HxTaU5AyfGRzdL6WGh+rACP3L/yLM7+nosB2uYWkcVcBux+uCpNpxkGBrmelibbBg75Q8zSC6elF8gJzx4/bCg4PyoFuAJN6EcvBjSl0nOd7sGQDOT0ftK+fuYAOV7c4VITRRgYDzVHXm9VqNFf43tD6IiWajKptp6igxHbmBxX8ygmsy5GhKA7ufr0DrcFuuJmSYFhg4nxTVW6Blqlvp3wv7fOEQYnNDzM/fLIOTiJ+bjQuG2YBudH/60Ho1jQSRksWnhfsKqm/8TopWniqaCpNgk7FfVopWp0E5AdzNvgTUGgfiNwD1lTTmevAnl1vQRLqnx/GygDC1mncf1ltiCHS/JNKsSUPuIWcQ6QfJ5IOs+ZBsh/FAqWl9EU+Hp4Jc1jGRM+XpWOeRxM+gahTXLp2C3dG6AjjzSr5nShgbjQ/y+bFPrdAljkaAYZiDA2DBEPg6NXzcP7i78zzF/scu09aXQzkAyxaGVDw/KdvA1uS9E/v6UDIhM2zzF65mbM0aeA="
